slawkens/myaac

system/pages/account/create_character.php

The latests clientes has a few problems to handle with strings above 21 lenghts on certain circumstances, and the min amount of three is too small to a name.
Also, remove a few trailling.

Increased the mininum lenght and decreased the maxinum lenght

---

config.php
system/pages/account/create_character.php

As requested in the previous PR. Let me know if the AAC has a style code to follow.

Sets the minimun lenght and maximun at config

---

TODO
config.php
system/pages/team.php
system/templates/team.html.twig

From TODO list, and some small changes with "width" in table.

Team page - display outfits of the players (configurable)

---

system/locale/pt_br/.htaccess
system/locale/pt_br/admin.php
system/locale/pt_br/install.php
system/locale/pt_br/main.php
templates/tibiacom/news.tickers.html.twig

* add pt_br locale
* fix tickers canEdit butons on tibiacom template

some fixes

---

system/templates/guilds.view.html.twig

* problem that doesn't show the option to kick people from the guild

Removed unnecessary "if" in guild.view twig

---

.travis.yml
system/libs/pot/OTS_ServerStatus.php

* fixed mistype on `OTS_ServerStatus.php`
* added `.travis.yml`
this allows preventing merge PR with mistyping or break backward compatibility.
note: please squash xd

* added travisci to prevent mistype

---

config.php
index.php
system/pages/bans.php
system/templates/bans.html.twig

Please review if all ok, then I will merge :P
@whiteblXK @Leesneaks
I have tested on TFS 1.3 and TFS 0.3 rev 3777.

Bans page working for TFS 1.x + move to Twig

---

index.php

Updating for new SPL standard.

Update 404 response

---

system/pages/guilds/change_rank.php

as per https://otland.net/threads/gesior2012-and-myaac-bug-release-2022-04-26-at-21-00-cet.280732/#post-2693021

Patch vulnerability in change_rank.php

---

config.php
system/libs/CreateCharacter.php

feat: config use character sample skill

---

config.php
system/libs/validator.php

allow easy blocking: prefix, name, and word in character name

feat: custom words blocked

---

.github/workflows/phplint.yml
system/bin/clear_cache.php

run phplint on actions below:
- pull requests, if target branches are master or develop
- push, if the target branch is the branch develop
----

feat: github actions phplint

---

system/templates/admin.news.form.html.twig

Update admin.news.form.html.twig (typo fix: rename Ticket to Ticker)

---

admin/template/menus.php
system/pages/admin/tools.php
system/pages/admin/tools/account.php
system/pages/admin/tools/teleport.php
system/templates/admin.tools.account.html.twig
system/templates/admin.tools.teleport.html.twig

- mass account tool
- coins (if coins column exists)
- points (if premium_points column exists)
- premdays (if (premdays and lastday) or premend or premium_ends_at exists)
- mass teleport tool (make sure there is nobody logged in)
- update town
- update position
- reset position to temple
------

feat: mass account tool, mass teleport tool

---

common.php
install/includes/schema.sql
system/libs/creatures.php
system/libs/pot/OTS_Monster.php
system/migrations/35.php

Added attributes from the monster look to the db (type, head, body, legs, feet, addons and corpse)

[UPDATE] Adding monster looks to db

---

cypress/e2e/3-check-public-pages.cy.js
cypress/e2e/4-check-protected-pages.cy.js
package.json

ensuring the page's reachability and checking protected pages.

feat: add more tests

---

cypress/e2e/2-create-account.cy.js
system/pages/account/change_password.php
system/pages/account/create.php
system/templates/account.change_password.html.twig
system/templates/account.create.html.twig
system/templates/account.create.js.html.twig
tools/validate.php

A small correction to the naming of the password2 variable.

fix: password2 variable refactor to correct name

---

system/pages/forum/show_board.php

We have to login first to see new thread button.

fix: require login before create new thread

---

system/pages/highscores.php
system/src/Models/PlayerKillers.php

highscore frags was not finding the table, and if it was found it returned 0.

frag highscore fixed

---

admin/pages/accounts.php
admin/pages/mailer.php
admin/pages/mass_account.php
admin/pages/players.php

fixes:
- accounts - required min size for search by account number
- accounts - search by email
- mass_accounts - drop raw queries & removed old code
chore:
- mailer - drop raw queries

chore: drop raw queries

---

login.php
system/pages/account/login.php
system/settings.php
system/src/RateLimit.php

new settings for set up IP ban protection after exceeding incorrect login attempts.
- new tab security
- enable rate limit for login php and login via web

feat: ratelimit
